#!/usr/bin/env bash

set -eou pipefail

nj=16
stage=-1
stop_stage=3

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/LibriTTS
#      You can download LibriTTS from https://www.openslr.org/60/
#

dl_dir=$PWD/download

# dataset_parts="dev-clean test-clean"  # debug
dataset_parts="auto"  # all

. shared/parse_options.sh || exit 1


# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ "${dataset_parts}" == "auto" ];then
  dataset_parts_opts="--dataset-parts=auto"
else
  dataset_parts_opts=""
  for part in `echo ${dataset_parts} | cut -d" " -f1-`;do
    dataset_parts_opts="${dataset_parts_opts} -p ${part}"
  done
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  # If you have pre-downloaded it to /path/to/LibriTTS,
  # you can create a symlink
  #
  #   ln -sfv /path/to/LibriTTS $dl_dir/LibriTTS
  #
  if [ ! -d $dl_dir/LibriTTS/dev-clean ]; then
    # lhotse download libritts $dl_dir
    lhotse download libritts ${dataset_parts_opts} $dl_dir
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare LibriTTS manifest"
  # We assume that you have downloaded the LibriTTS corpus
  # to $dl_dir/LibriTTS
  mkdir -p data/manifests
  if [ ! -e data/manifests/.libritts.done ]; then
    lhotse prepare libritts ${dataset_parts_opts} -j $nj $dl_dir/LibriTTS data/manifests
    touch data/manifests/.libritts.done
  fi
fi


if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Tokenize LibriTTS"
  mkdir -p data/tokenized
  if [ ! -e data/tokenized/.libritts.tokenize.done ]; then
    python3 bin/tokenizer.py --dataset-parts "${dataset_parts}" \
        --src-dir "data/manifests" \
        --output-dir "data/tokenized"
  fi
  touch data/tokenized/.libritts.tokenize.done
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Prepare LibriTTS train/dev/test"
  if [ ! -e data/tokenized/.libritts.train.done ]; then
    if [ "${dataset_parts}" == "auto" ];then
      # train
      lhotse combine \
        data/tokenized/libritts_cuts_train-clean-100.jsonl.gz \
        data/tokenized/libritts_cuts_train-clean-360.jsonl.gz \
        data/tokenized/libritts_cuts_train-other-500.jsonl.gz \
        data/tokenized/cuts_train.jsonl.gz

      # dev
      lhotse copy \
        data/tokenized/libritts_cuts_dev-clean.jsonl.gz \
        data/tokenized/cuts_dev.jsonl.gz
    else  # debug
      # train
      lhotse copy \
        data/tokenized/libritts_cuts_dev-clean.jsonl.gz \
        data/tokenized/cuts_train.jsonl.gz
      # dev
      lhotse subset --first 400 \
        data/tokenized/libritts_cuts_test-clean.jsonl.gz \
        data/tokenized/cuts_dev.jsonl.gz
    fi

    # test
    lhotse copy \
      data/tokenized/libritts_cuts_test-clean.jsonl.gz \
      data/tokenized/cuts_test.jsonl.gz

    touch data/tokenized/.libritts.train.done
  fi
fi

exit 0

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Train LibriTTS"

  # nano
  python3 bin/trainer.py \
    --decoder-dim 128 --nhead 4 --num-decoder-layers 4 \
    --exp-dir exp/valle_nano

  # same as paper
  python3 bin/trainer.py \
    --decoder-dim 1024 --nhead 16 --num-decoder-layers 12 \
    --exp-dir exp/valle
fi
